In [1]:
import gym
print(gym.__version__)

0.26.2


In [3]:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
     env.render()
     env.step(env.action_space.sample()) # take a random action env.close()

C:\Users\MUSFIQ\anaconda3\Lib\site-packages\gym\envs\registration.py:555: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(
C:\Users\MUSFIQ\anaconda3\Lib\site-packages\gym\envs\classic_control\cartpole.py:211: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v0", render_mode="rgb_array")
  gym.logger.warn(
C:\Users\MUSFIQ\anaconda3\Lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):
C:\Users\MUSFIQ\anaconda3\Lib\site-packages\gym\envs\classic_control\cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further 

In [5]:
import gym
import matplotlib.pyplot as plt

env = gym.make('CartPole-v1', render_mode='rgb_array')  # Use 'rgb_array' for Jupyter
obs = env.reset()

frames = []
for _ in range(100):
    frames.append(env.render())  # Collect frames
    action = env.action_space.sample()
    env.step(action)

env.close()

# Display one frame
plt.imshow(frames[0])
plt.axis('off')
plt.show()


DependencyNotInstalled: pygame is not installed, run `pip install gym[classic_control]`

In [7]:
!pip install gym[classic_control]

     ---------------------------------------- 0.0/5.8 MB ? eta -:--:--
     - -------------------------------------- 0.3/5.8 MB ? eta -:--:--
     --------- ------------------------------ 1.3/5.8 MB 4.5 MB/s eta 0:00:01
     ------------------------- -------------- 3.7/5.8 MB 7.8 MB/s eta 0:00:01
     ---------------------------------------- 5.8/5.8 MB 8.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [81 lines of output]
  
  
  WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
  Using WINDOWS configuration...
  
  Traceback (most recent call last):
    File "C:\Users\MUSFIQ\AppData\Local\Temp\pip-install-z_aai0h7\pygame_915a53fe411d44b39f4968bfce7f0d7b\buildconfig\config_win.py", line 336, in configure
      from . import vstools
    File "C:\Users\MUSFIQ\AppData\Local\Temp\pip-install-z_aai0h7\pygame_915a53fe411d44b39f4968bfce7f0d7b\buildconfig\vstools.py", line 5, in <module>
      from distutils.msvccompiler import MSVCCompiler, get_build_architecture
  ModuleNotFoundError: No module named 'distutils.msvccompiler'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\MUSFIQ\AppD

In [2]:
import numpy as np

# Assuming you have defined the number of states and actions

num_states = 10  # Example number of states

num_actions = 5  # Example number of actions

# Initialize Q-table with zeros

Q_table = np.zeros((num_states, num_actions))

# Print initial Q-table

print("Initial Q-Table:")

print(Q_table)

Initial Q-Table:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
